<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php
if( $_product->getTypeId() == 'elbasri_gold' && $_product->getAllowproductview() && 1==2):

?>
<div class="box-tocart">
  <div class="fieldset">
    <div class="actions"> 
	   	<a target="<?php echo $_product->getOpenin() ?>" href="<?php echo $_product->getLinkurl() ?>" > 		
        		<span class="action tocart primary" style="text-align:center">
                	<span>
                    	<span><?php echo $_product->getLinetext() ?></span>
                    </span>
                 </span>
          </a>
        
     </div>
  </div>
</div>
<?php
elseif ($_product->isSaleable()): 
?>
<div class="box-tocart">
  <div class="fieldset">
    <?php if ($block->shouldRenderQuantity()): ?>
    <div class="field qty">
      <label class="label" for="qty"><span>
        <?php /* @escapeNotVerified */ echo __('Qty') ?>
        </span></label>
      <div class="control">
        <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
      </div>
    </div>
    <?php endif; ?>
    <div class="actions">
      <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"> <span>
      <?php /* @escapeNotVerified */ echo $buttonTitle ?>
      </span> </button>
      <?php echo $block->getChildHtml('', true) ?> </div>
  </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
